// <auto-generated />
using BookSell.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSell.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240412055749_deletingPriceColumnFromCategory")]
    partial class deletingPriceColumnFromCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSell.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = "1",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = "2",
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = "3",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BookSell.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = " Dave Eggers",
                            CategoryId = 1,
                            Description = "A Heartbreaking Work of Staggering Genius is the moving memoir of a college senior who, in the space of five weeks, loses both of his parents to cancer and inherits his eight-year-old brother. This exhilarating debut that manages to be simultaneously hilarious and wildly inventive as well as a deeply heartfelt story of the love that holds a family together.",
                            ISBN = "0375725784",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "A Heartbreaking Work of Staggering Genius: Pulitzer Prize Finalist "
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ishmael Beah",
                            CategoryId = 1,
                            Description = "This is how wars are fought now: by children, hopped-up on drugs and wielding AK-47s. Children have become soldiers of choice. In the more than fifty conflicts going on worldwide, it is estimated that there are some 300,000 child soldiers. Ishmael Beah used to be one of them.",
                            ISBN = "9780374531263",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Long Way Gone"
                        },
                        new
                        {
                            Id = 3,
                            Author = " Ernest Hemingway",
                            CategoryId = 1,
                            Description = "Published posthumously in 1964, A Moveable Feast remains one of Ernest Hemingway’s most enduring works. Since Hemingway’s personal papers were released in 1979, scholars have examined the changes made to the text before publication. Now, this special restored edition presents the original manuscript as the author prepared it to be published.",
                            ISBN = "143918271X",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "A Moveable Feast: The Restored Edition"
                        },
                        new
                        {
                            Id = 4,
                            Author = "William Manchester",
                            CategoryId = 2,
                            Description = "Inspiring, outrageous... A thundering paradox of a man. Douglas MacArthur, one of only five men in history to have achieved the rank of General of the United States Army. He served in World Wars I, II, and the Korean War, and is famous for stating that \"in war, there is no substitute for victory.\"\r\n",
                            ISBN = "0316024740",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "American Caesar: Douglas MacArthur 1880 - 1964"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Kai Bird, Martin J. Sherwin",
                            CategoryId = 2,
                            Description = "THE INSPIRATION FOR THE ACADEMY AWARD®-WINNING MAJOR MOTION PICTURE OPPENHEIMER • \"A riveting account of one of history’s most essential and paradoxical figures.”—Christopher Nolan",
                            ISBN = "0375726268",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "American Prometheus: The Inspiration for the Major Motion Picture OPPENHEIMER "
                        },
                        new
                        {
                            Id = 6,
                            Author = "Patti Smith",
                            CategoryId = 3,
                            Description = "“Reading rocker Smith’s account of her relationship with photographer Robert Mapplethorpe, it’s hard not to believe in fate. How else to explain the chance encounter that threw them together, allowing both to blossom? Quirky and spellbinding.” -- People",
                            ISBN = "0060936228",
                            ImageURL = "",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Just Kids: A National Book Award Winner"
                        });
                });

            modelBuilder.Entity("BookSell.Models.Product", b =>
                {
                    b.HasOne("BookSell.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
